package Projetos.Controll;
// Generated 22/01/2016 10:59:18 by Hibernate Tools 4.3.1



/**
 * AtividadeId generated by hbm2java
 */
public class AtividadeId  implements java.io.Serializable {


     private String idproj;
     private int sequencia;

    public AtividadeId() {
    }

    public AtividadeId(String idproj, int sequencia) {
       this.idproj = idproj;
       this.sequencia = sequencia;
    }
   
    public String getIdproj() {
        return this.idproj;
    }
    
    public void setIdproj(String idproj) {
        this.idproj = idproj;
    }
    public int getSequencia() {
        return this.sequencia;
    }
    
    public void setSequencia(int sequencia) {
        this.sequencia = sequencia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AtividadeId) ) return false;
		 AtividadeId castOther = ( AtividadeId ) other; 
         
		 return ( (this.getIdproj()==castOther.getIdproj()) || ( this.getIdproj()!=null && castOther.getIdproj()!=null && this.getIdproj().equals(castOther.getIdproj()) ) )
 && (this.getSequencia()==castOther.getSequencia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdproj() == null ? 0 : this.getIdproj().hashCode() );
         result = 37 * result + this.getSequencia();
         return result;
   }   


}


