package Projetos.Controll;
// Generated 22/01/2016 10:59:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Atividade generated by hbm2java
 */
public class Atividade  implements java.io.Serializable {


     private AtividadeId id;
     private Fase fase;
     private String nome;
     private Date datainiprev;
     private Date datafimprev;
     private Date datainireal;
     private Date datafimreal;
     private String horainiprev;
     private String horafimprev;
     private String horainireal;
     private String horafimreal;
     private BigDecimal duracaoest;
     private BigDecimal duracaoreal;
     private BigDecimal custoest;
     private BigDecimal custoreal;
     private String status;
     private Set dependeciaativs = new HashSet(0);
     private Set participanteativs = new HashSet(0);
     private Set ocorrencias = new HashSet(0);

    public Atividade() {
    }

	
    public Atividade(AtividadeId id, Fase fase, String nome, Date datainiprev, Date datafimprev, BigDecimal duracaoest, BigDecimal custoest, String status) {
        this.id = id;
        this.fase = fase;
        this.nome = nome;
        this.datainiprev = datainiprev;
        this.datafimprev = datafimprev;
        this.duracaoest = duracaoest;
        this.custoest = custoest;
        this.status = status;
    }
    public Atividade(AtividadeId id, Fase fase, String nome, Date datainiprev, Date datafimprev, Date datainireal, Date datafimreal, String horainiprev, String horafimprev, String horainireal, String horafimreal, BigDecimal duracaoest, BigDecimal duracaoreal, BigDecimal custoest, BigDecimal custoreal, String status, Set dependeciaativs, Set participanteativs, Set ocorrencias) {
       this.id = id;
       this.fase = fase;
       this.nome = nome;
       this.datainiprev = datainiprev;
       this.datafimprev = datafimprev;
       this.datainireal = datainireal;
       this.datafimreal = datafimreal;
       this.horainiprev = horainiprev;
       this.horafimprev = horafimprev;
       this.horainireal = horainireal;
       this.horafimreal = horafimreal;
       this.duracaoest = duracaoest;
       this.duracaoreal = duracaoreal;
       this.custoest = custoest;
       this.custoreal = custoreal;
       this.status = status;
       this.dependeciaativs = dependeciaativs;
       this.participanteativs = participanteativs;
       this.ocorrencias = ocorrencias;
    }
   
    public AtividadeId getId() {
        return this.id;
    }
    
    public void setId(AtividadeId id) {
        this.id = id;
    }
    public Fase getFase() {
        return this.fase;
    }
    
    public void setFase(Fase fase) {
        this.fase = fase;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDatainiprev() {
        return this.datainiprev;
    }
    
    public void setDatainiprev(Date datainiprev) {
        this.datainiprev = datainiprev;
    }
    public Date getDatafimprev() {
        return this.datafimprev;
    }
    
    public void setDatafimprev(Date datafimprev) {
        this.datafimprev = datafimprev;
    }
    public Date getDatainireal() {
        return this.datainireal;
    }
    
    public void setDatainireal(Date datainireal) {
        this.datainireal = datainireal;
    }
    public Date getDatafimreal() {
        return this.datafimreal;
    }
    
    public void setDatafimreal(Date datafimreal) {
        this.datafimreal = datafimreal;
    }
    public String getHorainiprev() {
        return this.horainiprev;
    }
    
    public void setHorainiprev(String horainiprev) {
        this.horainiprev = horainiprev;
    }
    public String getHorafimprev() {
        return this.horafimprev;
    }
    
    public void setHorafimprev(String horafimprev) {
        this.horafimprev = horafimprev;
    }
    public String getHorainireal() {
        return this.horainireal;
    }
    
    public void setHorainireal(String horainireal) {
        this.horainireal = horainireal;
    }
    public String getHorafimreal() {
        return this.horafimreal;
    }
    
    public void setHorafimreal(String horafimreal) {
        this.horafimreal = horafimreal;
    }
    public BigDecimal getDuracaoest() {
        return this.duracaoest;
    }
    
    public void setDuracaoest(BigDecimal duracaoest) {
        this.duracaoest = duracaoest;
    }
    public BigDecimal getDuracaoreal() {
        return this.duracaoreal;
    }
    
    public void setDuracaoreal(BigDecimal duracaoreal) {
        this.duracaoreal = duracaoreal;
    }
    public BigDecimal getCustoest() {
        return this.custoest;
    }
    
    public void setCustoest(BigDecimal custoest) {
        this.custoest = custoest;
    }
    public BigDecimal getCustoreal() {
        return this.custoreal;
    }
    
    public void setCustoreal(BigDecimal custoreal) {
        this.custoreal = custoreal;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getDependeciaativs() {
        return this.dependeciaativs;
    }
    
    public void setDependeciaativs(Set dependeciaativs) {
        this.dependeciaativs = dependeciaativs;
    }
    public Set getParticipanteativs() {
        return this.participanteativs;
    }
    
    public void setParticipanteativs(Set participanteativs) {
        this.participanteativs = participanteativs;
    }
    public Set getOcorrencias() {
        return this.ocorrencias;
    }
    
    public void setOcorrencias(Set ocorrencias) {
        this.ocorrencias = ocorrencias;
    }




}


