package Projetos.Controll;
// Generated 22/01/2016 10:59:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int codcli;
     private Cidade cidade;
     private String nome;
     private String endereco;
     private Set pessoas = new HashSet(0);
     private Set projetos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int codcli, Cidade cidade) {
        this.codcli = codcli;
        this.cidade = cidade;
    }
    public Cliente(int codcli, Cidade cidade, String nome, String endereco, Set pessoas, Set projetos) {
       this.codcli = codcli;
       this.cidade = cidade;
       this.nome = nome;
       this.endereco = endereco;
       this.pessoas = pessoas;
       this.projetos = projetos;
    }
   
    public int getCodcli() {
        return this.codcli;
    }
    
    public void setCodcli(int codcli) {
        this.codcli = codcli;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }
    public Set getProjetos() {
        return this.projetos;
    }
    
    public void setProjetos(Set projetos) {
        this.projetos = projetos;
    }




}


