package Projetos.Controll;
// Generated 22/01/2016 10:59:18 by Hibernate Tools 4.3.1



/**
 * Dependeciaativ generated by hbm2java
 */
public class Dependeciaativ  implements java.io.Serializable {


     private DependeciaativId id;
     private Atividade atividade;

    public Dependeciaativ() {
    }

    public Dependeciaativ(DependeciaativId id, Atividade atividade) {
       this.id = id;
       this.atividade = atividade;
    }
   
    public DependeciaativId getId() {
        return this.id;
    }
    
    public void setId(DependeciaativId id) {
        this.id = id;
    }
    public Atividade getAtividade() {
        return this.atividade;
    }
    
    public void setAtividade(Atividade atividade) {
        this.atividade = atividade;
    }




}


