package Projetos.Controll;
// Generated 22/01/2016 10:59:18 by Hibernate Tools 4.3.1



/**
 * DependeciaativId generated by hbm2java
 */
public class DependeciaativId  implements java.io.Serializable {


     private String idproj;
     private int sequencia;
     private int sequenciadep;

    public DependeciaativId() {
    }

    public DependeciaativId(String idproj, int sequencia, int sequenciadep) {
       this.idproj = idproj;
       this.sequencia = sequencia;
       this.sequenciadep = sequenciadep;
    }
   
    public String getIdproj() {
        return this.idproj;
    }
    
    public void setIdproj(String idproj) {
        this.idproj = idproj;
    }
    public int getSequencia() {
        return this.sequencia;
    }
    
    public void setSequencia(int sequencia) {
        this.sequencia = sequencia;
    }
    public int getSequenciadep() {
        return this.sequenciadep;
    }
    
    public void setSequenciadep(int sequenciadep) {
        this.sequenciadep = sequenciadep;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DependeciaativId) ) return false;
		 DependeciaativId castOther = ( DependeciaativId ) other; 
         
		 return ( (this.getIdproj()==castOther.getIdproj()) || ( this.getIdproj()!=null && castOther.getIdproj()!=null && this.getIdproj().equals(castOther.getIdproj()) ) )
 && (this.getSequencia()==castOther.getSequencia())
 && (this.getSequenciadep()==castOther.getSequenciadep());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdproj() == null ? 0 : this.getIdproj().hashCode() );
         result = 37 * result + this.getSequencia();
         result = 37 * result + this.getSequenciadep();
         return result;
   }   


}


