package Projetos.Controll;
// Generated 22/01/2016 10:59:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fase generated by hbm2java
 */
public class Fase  implements java.io.Serializable {


     private int codfase;
     private String nome;
     private Set projetos = new HashSet(0);
     private Set atividades = new HashSet(0);

    public Fase() {
    }

	
    public Fase(int codfase) {
        this.codfase = codfase;
    }
    public Fase(int codfase, String nome, Set projetos, Set atividades) {
       this.codfase = codfase;
       this.nome = nome;
       this.projetos = projetos;
       this.atividades = atividades;
    }
   
    public int getCodfase() {
        return this.codfase;
    }
    
    public void setCodfase(int codfase) {
        this.codfase = codfase;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getProjetos() {
        return this.projetos;
    }
    
    public void setProjetos(Set projetos) {
        this.projetos = projetos;
    }
    public Set getAtividades() {
        return this.atividades;
    }
    
    public void setAtividades(Set atividades) {
        this.atividades = atividades;
    }




}


