package Projetos.Controll;
// Generated 22/01/2016 10:59:18 by Hibernate Tools 4.3.1



/**
 * Ocorrencia generated by hbm2java
 */
public class Ocorrencia  implements java.io.Serializable {


     private OcorrenciaId id;
     private Atividade atividade;
     private String descricao;

    public Ocorrencia() {
    }

	
    public Ocorrencia(OcorrenciaId id, Atividade atividade) {
        this.id = id;
        this.atividade = atividade;
    }
    public Ocorrencia(OcorrenciaId id, Atividade atividade, String descricao) {
       this.id = id;
       this.atividade = atividade;
       this.descricao = descricao;
    }
   
    public OcorrenciaId getId() {
        return this.id;
    }
    
    public void setId(OcorrenciaId id) {
        this.id = id;
    }
    public Atividade getAtividade() {
        return this.atividade;
    }
    
    public void setAtividade(Atividade atividade) {
        this.atividade = atividade;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


