package Projetos.Controll;
// Generated 22/01/2016 10:59:18 by Hibernate Tools 4.3.1



/**
 * Participanteativ generated by hbm2java
 */
public class Participanteativ  implements java.io.Serializable {


     private ParticipanteativId id;
     private Atividade atividade;
     private Funcao funcao;
     private Pessoa pessoa;

    public Participanteativ() {
    }

    public Participanteativ(ParticipanteativId id, Atividade atividade, Funcao funcao, Pessoa pessoa) {
       this.id = id;
       this.atividade = atividade;
       this.funcao = funcao;
       this.pessoa = pessoa;
    }
   
    public ParticipanteativId getId() {
        return this.id;
    }
    
    public void setId(ParticipanteativId id) {
        this.id = id;
    }
    public Atividade getAtividade() {
        return this.atividade;
    }
    
    public void setAtividade(Atividade atividade) {
        this.atividade = atividade;
    }
    public Funcao getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }




}


