package Projetos.Controll;
// Generated 22/01/2016 10:59:18 by Hibernate Tools 4.3.1



/**
 * ParticipanteativId generated by hbm2java
 */
public class ParticipanteativId  implements java.io.Serializable {


     private String idproj;
     private int sequencia;
     private int codpess;

    public ParticipanteativId() {
    }

    public ParticipanteativId(String idproj, int sequencia, int codpess) {
       this.idproj = idproj;
       this.sequencia = sequencia;
       this.codpess = codpess;
    }
   
    public String getIdproj() {
        return this.idproj;
    }
    
    public void setIdproj(String idproj) {
        this.idproj = idproj;
    }
    public int getSequencia() {
        return this.sequencia;
    }
    
    public void setSequencia(int sequencia) {
        this.sequencia = sequencia;
    }
    public int getCodpess() {
        return this.codpess;
    }
    
    public void setCodpess(int codpess) {
        this.codpess = codpess;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParticipanteativId) ) return false;
		 ParticipanteativId castOther = ( ParticipanteativId ) other; 
         
		 return ( (this.getIdproj()==castOther.getIdproj()) || ( this.getIdproj()!=null && castOther.getIdproj()!=null && this.getIdproj().equals(castOther.getIdproj()) ) )
 && (this.getSequencia()==castOther.getSequencia())
 && (this.getCodpess()==castOther.getCodpess());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdproj() == null ? 0 : this.getIdproj().hashCode() );
         result = 37 * result + this.getSequencia();
         result = 37 * result + this.getCodpess();
         return result;
   }   


}


