package Projetos.Controll;
// Generated 22/01/2016 10:59:18 by Hibernate Tools 4.3.1



/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private int codpess;
     private Pessoa pessoa;
     private String name;

    public Person() {
    }

    public Person(Pessoa pessoa, String name) {
       this.pessoa = pessoa;
       this.name = name;
    }
   
    public int getCodpess() {
        return this.codpess;
    }
    
    public void setCodpess(int codpess) {
        this.codpess = codpess;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


