package Projetos.Controll;
// Generated 22/01/2016 10:59:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Projeto generated by hbm2java
 */
public class Projeto  implements java.io.Serializable {


     private String idproj;
     private Cliente cliente;
     private String nome;
     private String tipo;
     private Date datainiprev;
     private Date datafimprev;
     private Date datainireal;
     private Date datafimreal;
     private BigDecimal custoest;
     private Set fases = new HashSet(0);

    public Projeto() {
    }

	
    public Projeto(String idproj, Cliente cliente, String nome, String tipo, Date datainiprev, Date datafimprev) {
        this.idproj = idproj;
        this.cliente = cliente;
        this.nome = nome;
        this.tipo = tipo;
        this.datainiprev = datainiprev;
        this.datafimprev = datafimprev;
    }
    public Projeto(String idproj, Cliente cliente, String nome, String tipo, Date datainiprev, Date datafimprev, Date datainireal, Date datafimreal, BigDecimal custoest, Set fases) {
       this.idproj = idproj;
       this.cliente = cliente;
       this.nome = nome;
       this.tipo = tipo;
       this.datainiprev = datainiprev;
       this.datafimprev = datafimprev;
       this.datainireal = datainireal;
       this.datafimreal = datafimreal;
       this.custoest = custoest;
       this.fases = fases;
    }
   
    public String getIdproj() {
        return this.idproj;
    }
    
    public void setIdproj(String idproj) {
        this.idproj = idproj;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getDatainiprev() {
        return this.datainiprev;
    }
    
    public void setDatainiprev(Date datainiprev) {
        this.datainiprev = datainiprev;
    }
    public Date getDatafimprev() {
        return this.datafimprev;
    }
    
    public void setDatafimprev(Date datafimprev) {
        this.datafimprev = datafimprev;
    }
    public Date getDatainireal() {
        return this.datainireal;
    }
    
    public void setDatainireal(Date datainireal) {
        this.datainireal = datainireal;
    }
    public Date getDatafimreal() {
        return this.datafimreal;
    }
    
    public void setDatafimreal(Date datafimreal) {
        this.datafimreal = datafimreal;
    }
    public BigDecimal getCustoest() {
        return this.custoest;
    }
    
    public void setCustoest(BigDecimal custoest) {
        this.custoest = custoest;
    }
    public Set getFases() {
        return this.fases;
    }
    
    public void setFases(Set fases) {
        this.fases = fases;
    }




}


